### ISSUE TITLE
Ability to set line spacing

### ISSUE THREAD

**Issue by jharbert** [nickfrandsen/htmltoword#20]
This is a feature request to add the ability to set line spacing on a body or paragraph level (similar to #19)

The line spacing is set on paragraph level with a line spacing of 1 set to the value 240, 1.5 is then 360, and 2 is 480.

The following paragraph property seems to work:

```
<w:pPr>
  <w:spacing w:line="480" />
</w:pPr>
```

**Comment by MadsBuus** [comment]
Hmm, in the maintained version of this gem here: https://github.com/karnov/htmltoword
We had a lot of markdown we needed to get into some pretty word documents. Adding 'blank' lines is always eaten by the markdown converter, so we decided to use the blockquote syntax
> (this will create an empty line in word()
>>>  (this will create 3)

We are actually mis-using the 'blockquote' so inserting blockquotes will give you a blank line in word.
(since this is kind of a 'hack', you will currently need to use the 'extras' option when calling htmltoword

**Comment by anitsirc** [comment]
You can also define and use you're own word document template, where you set up the styles customized for your needs. There you set up paragraph spacing (before and after), font family, font size, etc. 

Currently we are transforming to Heading1, Heading2, Heading3, Heading4 and Normal.
